# try_catch.coffee

console.log (
    try
      100 / 0
    catch e
      "the error is #{e}"
  )
# => Infinity
